ELASTIC_HOST = "http://localhost:9200"
CSV_URL = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
INDEX_NAME = "covid19_cases"
CSV_FILE_NAME = "time_series_covid19_confirmed_global.csv"
DATA_DIR = "data"